//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Flexar.Grammar/Flexar.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FlexarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IFlexarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] FlexarParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.program_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram_rule([NotNull] FlexarParser.Program_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.import_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_group([NotNull] FlexarParser.Import_groupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.import_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_rule([NotNull] FlexarParser.Import_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.import_namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_namespace([NotNull] FlexarParser.Import_namespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.namespace_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_name([NotNull] FlexarParser.Namespace_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace([NotNull] FlexarParser.NamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.namespace_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_call([NotNull] FlexarParser.Namespace_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass([NotNull] FlexarParser.ClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.class_extends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_extends([NotNull] FlexarParser.Class_extendsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.class_implements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_implements([NotNull] FlexarParser.Class_implementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.class_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_body([NotNull] FlexarParser.Class_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.class_body_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_body_rule([NotNull] FlexarParser.Class_body_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.class_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_attribute([NotNull] FlexarParser.Class_attributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.privacy_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrivacy_modifier([NotNull] FlexarParser.Privacy_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.class_method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_method([NotNull] FlexarParser.Class_methodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.abstract_method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstract_method([NotNull] FlexarParser.Abstract_methodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.class_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_modifier([NotNull] FlexarParser.Class_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.constructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructor([NotNull] FlexarParser.ConstructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.class_new_instance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_new_instance([NotNull] FlexarParser.Class_new_instanceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.method_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_call([NotNull] FlexarParser.Method_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.attribute_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_call([NotNull] FlexarParser.Attribute_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface([NotNull] FlexarParser.InterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.interface_extends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_extends([NotNull] FlexarParser.Interface_extendsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.interface_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_body([NotNull] FlexarParser.Interface_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.interface_body_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_body_rule([NotNull] FlexarParser.Interface_body_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.interface_method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_method([NotNull] FlexarParser.Interface_methodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.interface_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_attribute([NotNull] FlexarParser.Interface_attributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct([NotNull] FlexarParser.StructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.struct_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_body([NotNull] FlexarParser.Struct_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.struct_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_attribute([NotNull] FlexarParser.Struct_attributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum([NotNull] FlexarParser.EnumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.enum_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_body([NotNull] FlexarParser.Enum_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.enum_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_attribute([NotNull] FlexarParser.Enum_attributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] FlexarParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.composed_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComposed_value([NotNull] FlexarParser.Composed_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.list_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_value([NotNull] FlexarParser.List_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.map_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMap_value([NotNull] FlexarParser.Map_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.tuple_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_value([NotNull] FlexarParser.Tuple_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.named_tuple_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamed_tuple_value([NotNull] FlexarParser.Named_tuple_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_expression([NotNull] FlexarParser.And_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr_expression([NotNull] FlexarParser.Or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.xor_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXor_expression([NotNull] FlexarParser.Xor_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.not_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot_expression([NotNull] FlexarParser.Not_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.expression_math"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_math([NotNull] FlexarParser.Expression_mathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.term_math"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_math([NotNull] FlexarParser.Term_mathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.factor_math"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_math([NotNull] FlexarParser.Factor_mathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.bitwise_math"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwise_math([NotNull] FlexarParser.Bitwise_mathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.shift_math"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_math([NotNull] FlexarParser.Shift_mathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.unary_math"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_math([NotNull] FlexarParser.Unary_mathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.before_unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBefore_unary([NotNull] FlexarParser.Before_unaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.after_unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAfter_unary([NotNull] FlexarParser.After_unaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.math_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMath_value([NotNull] FlexarParser.Math_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.parenthesis_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesis_expression([NotNull] FlexarParser.Parenthesis_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.bitwise_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwise_operator([NotNull] FlexarParser.Bitwise_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.shift_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_operator([NotNull] FlexarParser.Shift_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.term_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_operator([NotNull] FlexarParser.Term_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.factor_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_operator([NotNull] FlexarParser.Factor_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.comparision_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparision_operator([NotNull] FlexarParser.Comparision_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] FlexarParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] FlexarParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.new_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNew_scope([NotNull] FlexarParser.New_scopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.for_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_statement([NotNull] FlexarParser.For_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.for_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_rule([NotNull] FlexarParser.For_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.for_in"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_in([NotNull] FlexarParser.For_inContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.full_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFull_for([NotNull] FlexarParser.Full_forContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_statement([NotNull] FlexarParser.While_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.do_while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDo_while_statement([NotNull] FlexarParser.Do_while_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_statement([NotNull] FlexarParser.Switch_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.switch_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_case([NotNull] FlexarParser.Switch_caseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.try_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTry_statement([NotNull] FlexarParser.Try_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.catch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatch_statement([NotNull] FlexarParser.Catch_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.finally_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinally_statement([NotNull] FlexarParser.Finally_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] FlexarParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.elif_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElif_statement([NotNull] FlexarParser.Elif_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.else_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_statement([NotNull] FlexarParser.Else_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.struct_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_func([NotNull] FlexarParser.Struct_funcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc([NotNull] FlexarParser.FuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.anonymous_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymous_func([NotNull] FlexarParser.Anonymous_funcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.func_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_param([NotNull] FlexarParser.Func_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.func_callback"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_callback([NotNull] FlexarParser.Func_callbackContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.func_param_callback"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_param_callback([NotNull] FlexarParser.Func_param_callbackContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.func_param_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_param_rule([NotNull] FlexarParser.Func_param_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_call([NotNull] FlexarParser.Func_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.func_call_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_call_params([NotNull] FlexarParser.Func_call_paramsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.func_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_return([NotNull] FlexarParser.Func_returnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.func_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_body([NotNull] FlexarParser.Func_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] FlexarParser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declaration([NotNull] FlexarParser.Variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.variable_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_assign([NotNull] FlexarParser.Variable_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.variable_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_name([NotNull] FlexarParser.Variable_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.assing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssing([NotNull] FlexarParser.AssingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] FlexarParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlexarParser.final_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinal_type([NotNull] FlexarParser.Final_typeContext context);
}
